### PR TITLE
Extend Wallet holder_id property to support string type

### PR DESCRIPTION
**Pull request by adesege**
This PR extends wallet holder_id property to support string type.

In my use case, user id and item id are uuid strings.

### CODE REVIEW

**Comment by rez1dent3** [comment]
@adesege Maybe I'll pick up this MR, but definitely not in the near future.
1. The package supports php 7.4;
2. Contract and backward compatibility violated. This is only a major version;
At the moment, I'm throwing it on the back burner.

**Comment by adesege** [comment]
Hi @rez1dent3, thanks for the comment.

1. Union types was introduced in PHP 8.0. I can use psalm instead if you are okay with it.
2. I tried fixing this in my code but couldn't cos of the contract. I'm not sure it broke backward compatibility cos the methods accept integer or string. Those using integers will still be able to use it as expected.

I'm sure there are other people who use uuid strings as their primary id as well.

Let me know if there is a temporary way of solving this without extending core.

Thanks.

**Comment by rez1dent3** [comment]
@adesege There is another suggestion. I suggest postponing your pull request until laravel 9 is released. The new version will [remove support for php 7.4](https://github.com/laravel/laravel/blob/6808b20560faaa8e083e1ff4d96230878c1c72f3/composer.json#L8) and I was going to remove support for old laravel versions in laravel-wallet 8+.

**Comment by rez1dent3** [comment]
@adesege It was based #424 on your pull request. When the release of laravel 9 comes out and all the libraries are pulled up, I will release the release WITHOUT support for laravel 8.x. At the moment, I can only suggest using the dev version.
```bash
composer req bavix/laravel-wallet:dev-develop
```

**Comment by adesege** [comment]
Great! Laravel 9 will be released by Jan. 25th. I can wait till then. Thanks.

**Comment by adesege** [comment]
@rez1dent3 I've opened another PR to add string support for wallet id in transaction dto interface here https://github.com/bavix/laravel-wallet/pull/427

**Comment by rez1dent3** [comment]
@adesege hello. 
released version with laravel 9 support.
It included part by uuid.
tag 8.0.0

**Pull request merged**
