### PR TITLE
Fix transaction amount_float mutator

### PR DESCRIPTION
**Pull request by keatliang2005**
I have notice the mutator on the transaction model display somewhat funky. 

example i had the wallet set to 4 decimal precision, when access with `$model->amount_float`

i had `"0.0120000000000000000000000000000000000000000000000000000000000000"` as result

when i made changes above (on PR) it display correctly `"0.0120"`

### CODE REVIEW

**Comment by rez1dent3** [comment]
Hello. All right, thanks. I don't use float in my projects, so I didn't see the problem.
Please add unit tests and rebase with the master branch.

**Comment by keatliang2005** [comment]
Hi, I had added tests for the accessor fix

**Comment by rez1dent3** [comment]
The test is incorrect. I will take your PR as a basis and finalize it. Thank you very much.

**Comment by rez1dent3** [comment]
@keatliang2005 tag 9.0.4

**Pull request closed without merging**
