### PR TITLE
Global package update. 7x

### PR DESCRIPTION
**Pull request by rez1dent3**

### CODE REVIEW

**Comment by atymic** [comment]
Awesome work on the package @rez1dent3 

Will this release contain breaking changes?

**Comment by rez1dent3** [comment]
Yes, global package redesign. There are no release dates yet. While the design is underway.
@atymic FYI^

**Comment by rez1dent3** [comment]
see #346

**Comment by rez1dent3** [comment]
#347 bulk update, think over the design

**Comment by rez1dent3** [comment]
The project turned out to be too big. It was decided to break it down into 2 stages:
1. Infrastructure changes;
2. Changes to contracts;

The second stage will be the 7.x version, and the infrastructure ones will be introduced in the 6.x version. Version 6.x will most likely receive support from laravel 9. And already the version with new contracts will receive support only for laravel 9+.

**Pull request closed without merging**
