### PR TITLE
feat: updateOrAddMeta for wallet

### PR DESCRIPTION
**Pull request by justinkekeocha**
It will be nice to have a method that updates or adds a new key to the meta.

Just like what you did here: [https://github.com/bavix/laravel-wallet/issues/498#issuecomment-1124005291](url)

### CODE REVIEW

**Comment by justinkekeocha** [comment]
The code above does not remove existing records when saved, maybe you should actually run it.

**Comment by rez1dent3** [comment]
> The code above does not remove existing records when saved if that is what you mean. Maybe you should actually run the method.

I see and understand, I'm talking about the name and area of responsibility. The formation of a meta array is not the responsibility of the package.

**Comment by justinkekeocha** [comment]
Name can be changed to what will best describe it. I was just trying to add more helpers like the Eloquent updateOrCreate() method.

**Comment by rez1dent3** [comment]
I understand, but this is not the responsibility of the package. Here you need to approach conservatively, according to the principle of YAGNI (You Aren't Gonna Need It). The package develops from the feedback received, this functionality is superfluous. The more functions we add, the more difficult and expensive refactoring is. As part of the package, we do not solve the problems that developers have with php. Here we are developing an API for working on the wallet.

If you are looking for useful functionality, then please develop the balance with credit method. The point is to display the full balance along with the credit limit. You can read about the functionality here: https://bavix.github.io/laravel-wallet/#/credit-limits

**Comment by justinkekeocha** [comment]
I tried that, but it didn't work, which was was what set me searching.

**Comment by rez1dent3** [comment]
Sorry, I didn't catch the context. Can you tell me more about what you're talking about?

**Comment by justinkekeocha** [comment]
Quick question: supposing I want to extend the wallet.php model to add the feature for my own custom app. How would I do this. From going through the codebase, the MorphOne trait, has a wallet method which calls the wallet model. The getWalletAttribute() also calls a CastServiceInterface.

But I couldn't find a way to extend the model.

**Comment by rez1dent3** [comment]
@justinkekeocha You need to expand the model and replace it through the config.
https://github.com/bavix/laravel-wallet/blob/9b0bd38bd07d3d251cb6a48ae2eb11269a82342b/config/config.php#L184

Example `MyWallet.php`:
```php
use Bavix\Wallet\Models\Wallet as WalletBase;

class MyWallet extends WalletBase {
    public function helloWorld(): string { return "hello world"; }
}
```

`config/wallet.php`
```php
...
    'wallet' => [
        'table' => 'wallets',
        'model' => MyWallet::class,
        'creating' => [],
        'default' => [
            'name' => 'Default Wallet',
            'slug' => 'default',
            'meta' => [],
        ],
    ],
...
```

```php
echo $user->wallet->helloWorld();
```

**Comment by rez1dent3** [comment]
@justinkekeocha https://github.com/bavix/laravel-wallet/pull/769/files

**Comment by rez1dent3** [comment]
I don't see any benefit for the package with this PR, I'm really sorry. I'm closing the pull request.
Thank you for your contribution to the development of the project.

**Comment by justinkekeocha** [comment]
Can you please document this expansion, I really struggled to expand this model and I believe it is the same with other. If this will be much of a hassle for you, you can recommend which page I can put it in the documentation

**Comment by rez1dent3** [comment]
> Can you please document this expansion, I really struggled to expand this model and I believe it is the same with other. If this will be much of a hassle for you, you can recommend which page I can put it in the documentation

@justinkekeocha It seems to me that a new section in the documentation needs to be created for this. If you have a desire, please add.

**Comment by justinkekeocha** [comment]
I have done this here : [https://github.com/bavix/laravel-wallet/pull/770](url)

Is there a way to extend the Transaction and Transfer class?

I am guessing it is editing this

` /**
     * Base model 'transaction'.
     */
    'transaction' => [
        'table' => 'transactions',
        'model' => Transaction::class,
    ],

    /**
     * Base model 'transfer'.
     */
    'transfer' => [
        'table' => 'transfers',
        'model' => Transfer::class,
    ],`
    
    If yes, then let me go forward with the same way I did with the Wallet class

**Comment by rez1dent3** [comment]
Yes you are right. It's similar there.

**Pull request closed without merging**
